# GitHub Action
# Egyszerű példa a GitHub Action használatára
name: GitHub Action - Alap1

# Mikor futtassuk a workflow-t
on:
  # A Workflow a push és a pull_request eseményre fut le más-más branch-ekre
  push:
    branches: ["demo"]
  
  # Engedélyezzük a manuális futtatást is
  workflow_dispatch:

# Fő feladat
jobs:
  # Egyszerű build feladat
  build:
    # Milyen operációs rendszeren futtassuk a workflow-t
    runs-on: ubuntu-latest

    # Lépések sorban
    steps:
      # Először is töltsük le a repót
      - uses: actions/checkout@v3
      # Futassunk egy parancsot
      - name: Egy soros parancsok
        run: echo Hello, world!
      